version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=mydatabaseuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - '5432:5432'
    volumes:
      - ./dbvolume:/var/lib/postgresql/data
