# Generated by Django 4.1.5 on 2023-04-11 11:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_product_id_alter_stock_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTimeline",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity_change", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="api.product")),
                (
                    "vending_machine",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="api.vendingmachine"),
                ),
            ],
        ),
    ]
