# Generated by Django 4.1.5 on 2023-04-13 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_stocktimeline"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stocktimeline",
            old_name="quantity_change",
            new_name="quantity",
        ),
    ]
